---
- name: My Playbook for installing some packages
  hosts: all
  become: true
  tasks:
  - name: installing package
    yum:
      name: git
      state: installed
      name: httpd
      state: installed
      name: tree
      state: installed
...