---
- name: Tomcat Server Deploying to All Nodes
  hosts: all
  become: true

  tasks:
  - name: Installing Java in Redhat Linux
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  
  - name: Installing Java in Debian Family or UBUNTU
    apt:
      name: default-jdk
      state: installed
    when: ansible_os_family == "Debian"

  - name: Downloading Tomcat in Linux
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.16/bin/apache-tomcat-10.1.16.tar.gz
      dest: /opt

  - name: Extracting Tomcat Software
    unarchive:
      src: /opt/apache-tomcat-10.1.16.tar.gz
      dest: /opt
      remote_src: yes

  - name: Giving Executable file Permission to Shell Script file called startup.sh
    file:
      path: /opt/apache-tomcat-10.1.16/bin/startup.sh
      mode: 0777

  - name: starting Startup.sh file service for Tomcat
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-10.1.16/bin 

