---
- name: UnInstalling Httpd Package to server
  hosts: all
  become: true
  tasks:
  - name: Stopping the Service
    service:
      name: httpd
      state: stopped
  - name: Un-Installing Package
    yum:
     name: httpd
     state: removed

      