---
- name: installing Httpd Package to server
  hosts: all
  become: true
  tasks:
  - name: Installing Package
    yum:
     name: httpd
     state: installed
  - name: Starting Service
    service:
      name: httpd
      state: started
      